/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package source;


import java.awt.Button;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Map;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Marlic
 */
public class TicTacToePanel extends javax.swing.JPanel {

    public int algoritmo;
    static int jugada;
       static int input;
       static String finish;


    /**
     * Creates new form TicTacToePanel
     */
    public TicTacToePanel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMinimax = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPoda = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugar"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minimax", "Poda Alfa-Beta" }));

        jLabel2.setText("Algoritmo");

        btnPlay.setText("Jugar");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnClean.setText("Limpiar");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Estadisticas"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        btn1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel4.add(btn1);
        btn1.setBounds(30, 40, 130, 130);

        btn2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel4.add(btn2);
        btn2.setBounds(190, 40, 130, 130);

        btn3.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel4.add(btn3);
        btn3.setBounds(350, 40, 130, 130);

        btn4.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel4.add(btn4);
        btn4.setBounds(27, 210, 130, 110);

        btn5.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel4.add(btn5);
        btn5.setBounds(190, 210, 130, 110);

        btn6.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel4.add(btn6);
        btn6.setBounds(350, 210, 130, 110);

        btn7.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel4.add(btn7);
        btn7.setBounds(30, 370, 130, 130);

        btn8.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel4.add(btn8);
        btn8.setBounds(190, 370, 130, 130);

        btn9.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel4.add(btn9);
        btn9.setBounds(350, 370, 130, 130);

        jLabel11.setText("9.");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(350, 350, 45, 16);

        jLabel10.setText("8.");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(190, 350, 45, 16);

        jLabel9.setText("6.");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(350, 190, 45, 16);

        jLabel8.setText("7.");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(30, 350, 45, 16);

        jLabel7.setText("5.");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(190, 190, 45, 16);

        jLabel6.setText("4.");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(30, 190, 45, 16);

        jLabel5.setText("3.");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(360, 20, 45, 16);

        jLabel4.setText("2.");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(190, 20, 45, 16);

        jLabel3.setText("1.");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(30, 20, 45, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tictac4cm.png"))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(6, 6, 500, 500);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("minimax"));

        txtMinimax.setColumns(20);
        txtMinimax.setRows(5);
        jScrollPane1.setViewportView(txtMinimax);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("minimax con poda Alfa-Beta"));

        txtPoda.setColumns(20);
        txtPoda.setRows(5);
        jScrollPane2.setViewportView(txtPoda);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:

        /**
         * Recibe del teclado un numero correspondente al algoritmo escojido 1 -
         * Minimax 2 - Minimax com poda alpha-beta
         *
         * @return algoritmo escojido
         */
        String seleccionado = (String) jComboBox1.getSelectedItem();
        if (seleccionado == "Minimax") {
            algoritmo = 0;
               JOptionPane.showMessageDialog(this, "El juego a sido iniciado", "", JOptionPane.INFORMATION_MESSAGE);
        } else if (seleccionado == "Poda Alfa-Beta") {
            algoritmo = 1;
               JOptionPane.showMessageDialog(this, "El juego a sido iniciado", "", JOptionPane.INFORMATION_MESSAGE);
        } else {
            System.out.println("Ocurrio un error al escojer algoritmo");
        }
        juego();
      

    }//GEN-LAST:event_btnPlayActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed

    }//GEN-LAST:event_btn5ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed

    }//GEN-LAST:event_btn9ActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnCleanActionPerformed


    public void juego(){
                


        System.out.println("You are Player 1!");
        System.out.println("Current board:");
        source.Map.printBoard(source.Map.map);
        System.out.println("Please pick a field from 1-9:");
    //     String name = JOptionPane.showInputDialog("Please pick a field from 1-9:");
    ///    int input =Integer.parseInt(name);
    createAndDisplayGUI();
        setO(input);
       
        while (input < 1 || input > 9) {
            System.err.println("Please input a number between 1 and 9");
         //             name = JOptionPane.showInputDialog("Please pick a field from 1-9:");
        // input =Integer.parseInt(name);
            createAndDisplayGUI();
            setO(input);
        }

        source.Map.map = source.Map.setTile(source.Map.map, input - 1, 0);
        source.Map.moves.remove(input - 1);
        System.out.println("Current board:");
        source.Map.printBoard(source.Map.map);

        for (int i = 0; i < 4; i++) {
            // MiniMax Opponent
            if (algoritmo == 0) {
                long start = System.nanoTime();
                MiniMaxSearch.miniMax(1);
                long end = System.nanoTime() - start;
                               String textMinimax ="Posicion movimiento: "+ (source.Map.returnMove + 1) + "\n";
                  textMinimax = textMinimax +"Tiempo:  microsec = " +  end / 1_000d+"\n" ;
                    textMinimax = textMinimax +"estados visitados: "+ source.Map.visitedStates+ "\n";
                       textMinimax = textMinimax +"tiempo/estados: microsec "+ (end / 1_000d) / source.Map.visitedStates+"\n\n";

                       txtMinimax.append(textMinimax);
  
                System.out.println("Your opponent picked: " + (source.Map.returnMove + 1));
                   setX(source.Map.returnMove + 1);
                source.Map.map = source.Map.setTile(source.Map.map, source.Map.returnMove, 1);
                source.Map.moves.remove(source.Map.returnMove);
                System.out.println("Current board:");
                source.Map.printBoard(source.Map.map);
                if (checkWin()) {
                                JOptionPane.showMessageDialog(this, finish, "", JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
            }
            // Alpha-Beta Opponent
            else {
                long start = System.nanoTime();
                AlphaBetaSearch.alphaBetaSearch(1);
                long end = System.nanoTime() - start;
                String textAlpha ="Posicion movimiento: "+ (source.Map.returnMove + 1) + "\n";
                  textAlpha = textAlpha +"Tiempo:  microsec = " +  end / 1_000d+"\n" ;
                    textAlpha = textAlpha +"estados visitados: "+ source.Map.visitedStates+ "\n";
                       textAlpha = textAlpha +"tiempo/estados: microsec "+ (end / 1_000d) / source.Map.visitedStates+"\n\n";
                  //     txtPoda.setText(textAlpha);
                       txtPoda.append(textAlpha);
                 
                System.out.println("Your opponent picked: " + (source.Map.returnMove + 1));
                   setX(source.Map.returnMove + 1);
                source.Map.map = source.Map.setTile(source.Map.map, source.Map.returnMove, 1);
                source.Map.moves.remove(source.Map.returnMove);
                System.out.println("Current board:");
                source.Map.printBoard(source.Map.map);
                if (checkWin()) {
                                JOptionPane.showMessageDialog(this, finish, "", JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
            }

            System.out.println("Please pick a field from 1-9:");
    //            name = JOptionPane.showInputDialog("Please pick a field from 1-9:");
    //     input =Integer.parseInt(name);
        createAndDisplayGUI();
            setO(input);
            while (input < 1 || input > 9) {
                  System.err.println("Please input a number between 1 and 9");
       //           name = JOptionPane.showInputDialog("Please pick a field from 1-9:");
            //     input =Integer.parseInt(name);
                createAndDisplayGUI();
                 setO(input);
            }

            int tempMap = source.Map.setTile(source.Map.map, input - 1, 0);
            while (tempMap == Integer.MIN_VALUE) {
            //    input = sc.nextInt();
                createAndDisplayGUI();
                tempMap = source.Map.setTile(source.Map.map, input - 1, 0);
            }

            source.Map.map = source.Map.setTile(source.Map.map, input - 1, 0);
            source.Map.moves.remove(input - 1);
            System.out.println("Current board:");
            source.Map.printBoard(source.Map.map);
            if (checkWin()) {
                    JOptionPane.showMessageDialog(this, finish, "", JOptionPane.INFORMATION_MESSAGE);
                break;
            }

            source.Map.visitedStates = 0;
        }
    }
    
    
       private void createAndDisplayGUI()
       {       
           JOptionPane optionPane = new JOptionPane("Please pick a field from 1-9"
                                       , JOptionPane.PLAIN_MESSAGE
                                       , JOptionPane.DEFAULT_OPTION
                                       , null, null, "Please pick a field from 1-9");
           optionPane.setWantsInput(true);             
           JDialog dialog = optionPane.createDialog(null, "Tu Turno");
           dialog.setLocation(10, 20);
           dialog.setVisible(true);
           try{
           String name ="";
            name = (String) optionPane.getInputValue();
           input=0;
           System.out.println(name);
             input =Integer.parseInt(name);
           }catch(Exception e){
           JOptionPane.showMessageDialog(this, "Error al capturar numero: "+e, "Error",JOptionPane.ERROR_MESSAGE );
           }
       }

    private static boolean checkWin() {
        switch (source.Map.utility(source.Map.map)) {
            case 0:
                System.out.println("Game done!\nDraw!");
             finish ="Juego Terminado \n EMPATE!";
                return true;
            case 1:
                System.out.println("Game done!\nYour opponent wins!");
                        finish = "Juego Terminado \n COMPUTADORA GANA!";
                return true;
            case -1:
                System.out.println("Game done!\nYou win!");
                        finish ="Juego Terminado \n HAS GANADO!";
                return true;
        }

        return false;
    }
public void clear(){
       btn1.setText("");
       btn2.setText("");
       btn3.setText("");
       btn4.setText("");       
        btn5.setText("");
       btn6.setText("");
       btn7.setText("");
       btn8.setText("");     
       btn9.setText("");          

jugada=0;
  finish="";
  
source.Map.map=0;
source.Map.visitedStates = -10;

  // source.Map.returnMove = -1;

   source.Map.computerPlayer = -1;
   source.Map.message ="";
   source.Map.setHash();
}
    
public void setX(int posicion){
switch(posicion){
    case 1:
        btn1.setText("X");
       break;
     case 2:
        btn2.setText("X");         
       break; 
     case 3:
        btn3.setText("X");         
       break; 
     case 4:
         btn4.setText("X");        
       break;
     case 5:
         btn5.setText("X");        
       break; 
     case 6:
         btn6.setText("X");        
       break;          
    case 7:
        btn7.setText("X");        
       break;
     case 8:
        btn8.setText("X");         
       break; 
     case 9:
        btn9.setText("X");         
       break;
     default:
             JOptionPane.showMessageDialog(this, "ocurrio un error al mostrar la posicion", "", JOptionPane.ERROR_MESSAGE);
         break;
}

}

public void setO(int posicion){
switch(posicion){
    case 1:
        btn1.setText("O");
       break;
     case 2:
        btn2.setText("O");         
       break; 
     case 3:
        btn3.setText("O");         
       break; 
     case 4:
         btn4.setText("O");        
       break;
     case 5:
         btn5.setText("O");        
       break; 
     case 6:
         btn6.setText("O");        
       break;          
    case 7:
        btn7.setText("O");        
       break;
     case 8:
        btn8.setText("O");         
       break; 
     case 9:
        btn9.setText("O");         
       break;
     default:
             JOptionPane.showMessageDialog(this, "ocurrio un error al mostrar la posicion", "", JOptionPane.ERROR_MESSAGE);
         break;
}

}
    





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnPlay;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtMinimax;
    private javax.swing.JTextArea txtPoda;
    // End of variables declaration//GEN-END:variables

}
