/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package source;


import java.awt.BasicStroke;
import java.awt.Button;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.chart.NumberAxis;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.DefaultXYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Marlic
 */
public class TicTacToePanel extends javax.swing.JPanel {

        public int algoritmo;
        static int jugada;
        static int input;
        static String finish;
       
       // datos minimax
    //   static double[] time;
     //  static int[] states;
     //  static double[] timeState;
       ArrayList<Double> time = new ArrayList<Double>();
        ArrayList<Double> states = new ArrayList<Double>();
        ArrayList<Double> timeState = new ArrayList<Double>();
              
              //datos poda alpha-beta
       //static double[] timeAlpha;
       //static int[] statesAlpha;
        //static double[] timeStateAlpha;
               ArrayList<Double> timeAlpha = new ArrayList<Double>();
        ArrayList<Double> statesAlpha = new ArrayList<Double>();
        ArrayList<Double> timeStateAlpha = new ArrayList<Double>();


    /**
     * Creates new form TicTacToePanel
     */
    public TicTacToePanel() {
        initComponents();

btnTiempoEstados.setText("<html><p>Tiempo por</p><p>estados</p></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        btnStadistics = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnTiempo = new javax.swing.JButton();
        btnEstados = new javax.swing.JButton();
        btnTiempoEstados = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMinimax = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPoda = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugar"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minimax", "Poda Alfa-Beta" }));

        jLabel2.setText("Algoritmo");

        btnPlay.setText("Jugar");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnClean.setBackground(new java.awt.Color(255, 255, 255));
        btnClean.setForeground(new java.awt.Color(102, 102, 102));
        btnClean.setText("Limpiar");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        btnStadistics.setText("estadistica");
        btnStadistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStadisticsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStadistics, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnStadistics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Comparar metodos"));

        btnTiempo.setText("Tiempo");
        btnTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiempoActionPerformed(evt);
            }
        });

        btnEstados.setText("Estados");
        btnEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadosActionPerformed(evt);
            }
        });

        btnTiempoEstados.setText("jButton3");
        btnTiempoEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiempoEstadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTiempoEstados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTiempo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEstados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTiempoEstados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        btn1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel4.add(btn1);
        btn1.setBounds(30, 40, 130, 130);

        btn2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel4.add(btn2);
        btn2.setBounds(190, 40, 130, 130);

        btn3.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel4.add(btn3);
        btn3.setBounds(350, 40, 130, 130);

        btn4.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel4.add(btn4);
        btn4.setBounds(27, 210, 130, 110);

        btn5.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel4.add(btn5);
        btn5.setBounds(190, 210, 130, 110);

        btn6.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel4.add(btn6);
        btn6.setBounds(350, 210, 130, 110);

        btn7.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel4.add(btn7);
        btn7.setBounds(30, 370, 130, 130);

        btn8.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel4.add(btn8);
        btn8.setBounds(190, 370, 130, 130);

        btn9.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel4.add(btn9);
        btn9.setBounds(350, 370, 130, 130);

        jLabel11.setText("9.");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(350, 350, 45, 16);

        jLabel10.setText("8.");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(190, 350, 45, 16);

        jLabel9.setText("6.");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(350, 190, 45, 16);

        jLabel8.setText("7.");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(30, 350, 45, 16);

        jLabel7.setText("5.");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(190, 190, 45, 16);

        jLabel6.setText("4.");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(30, 190, 45, 16);

        jLabel5.setText("3.");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(360, 20, 45, 16);

        jLabel4.setText("2.");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(190, 20, 45, 16);

        jLabel3.setText("1.");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(30, 20, 45, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tictac4cm.png"))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(6, 6, 500, 500);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("minimax"));

        txtMinimax.setColumns(20);
        txtMinimax.setRows(5);
        jScrollPane1.setViewportView(txtMinimax);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("minimax con poda Alfa-Beta"));

        txtPoda.setColumns(20);
        txtPoda.setRows(5);
        jScrollPane2.setViewportView(txtPoda);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(819, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:

        /**
         * Recibe del teclado un numero correspondente al algoritmo escojido 1 -
         * Minimax 2 - Minimax com poda alpha-beta
         *
         * @return algoritmo escojido
         */
        String seleccionado = (String) jComboBox1.getSelectedItem();
        if (seleccionado == "Minimax") {
            algoritmo = 0;
               JOptionPane.showMessageDialog(this, "El juego a sido iniciado", "", JOptionPane.INFORMATION_MESSAGE);
        } else if (seleccionado == "Poda Alfa-Beta") {
            algoritmo = 1;
               JOptionPane.showMessageDialog(this, "El juego a sido iniciado", "", JOptionPane.INFORMATION_MESSAGE);
        } else {
            System.out.println("Ocurrio un error al escojer algoritmo");
        }
        juego();
      clear();
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed

    }//GEN-LAST:event_btn5ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed

    }//GEN-LAST:event_btn9ActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
        clear();
        time.clear();
        timeAlpha.clear();
        timeState.clear();
        timeStateAlpha.clear();
        states.clear();
        statesAlpha.clear();
        txtMinimax.setText("");
        txtPoda.setText("");
    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiempoActionPerformed
        // TODO add your handling code here:
        if (!time.isEmpty()) {
            if (!timeAlpha.isEmpty()) {
                 XYSeries series = new XYSeries("Minimax");
  XYSeries series1 = new XYSeries("Poda Alpha-Beta");

  
        for (int i = 0; i < time.size(); i++) {
            series.add(i+1, time.get(i));

        }
        
                for (int i = 0; i < timeAlpha.size(); i++) {
            series1.add(i+1, timeAlpha.get(i));
        }
    XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(series);
         dataset.addSeries(series1);
         
              JFreeChart chart = ChartFactory.createXYLineChart(
                "Tiempo de ejecucion turno", // Título
                "Turno", // Etiqueta Coordenada X
                "tiempo(Microsec)", // Etiqueta Coordenada Y
                dataset, // Datos
                PlotOrientation.VERTICAL,
                true, // Muestra la leyenda de los productos (Producto A)
                false,
                false
        );
              
        
                ChartFrame frame = new ChartFrame("Tiempo de ejecucion del turno ordenador", chart);
        frame.pack();
        frame.setVisible(true);
 
            }else{
                        JOptionPane.showMessageDialog(this, "Juega con el metodo Poda Alfa-Beta \n para crear comparacion", "No es posible comparar", JOptionPane.ERROR_MESSAGE);
            }
        } else{
                              JOptionPane.showMessageDialog(this, "Juega con el metodo minimax \n para crear comparacion", "No es posible comparar", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnTiempoActionPerformed

    private void btnEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadosActionPerformed
        // TODO add your handling code here:
                if (!states.isEmpty()) {
            if (!statesAlpha.isEmpty()) {
                 XYSeries series = new XYSeries("Minimax");
  XYSeries series1 = new XYSeries("Poda Alpha-Beta");

  
        for (int i = 0; i < states.size(); i++) {
            series.add(i+1, states.get(i));

        }
        
                for (int i = 0; i < statesAlpha.size(); i++) {
            series1.add(i+1, statesAlpha.get(i));
        }
    XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(series);
         dataset.addSeries(series1);
         
              JFreeChart chart = ChartFactory.createXYLineChart(
                "Estados", // Título
                "Turno", // Etiqueta Coordenada X
                "Num. de estados", // Etiqueta Coordenada Y
                dataset, // Datos
                PlotOrientation.VERTICAL,
                true, // Muestra la leyenda de los productos (Producto A)
                false,
                false
        );
              
        
                ChartFrame frame = new ChartFrame("Numero de estados del turno ordenador", chart);
        frame.pack();
        frame.setVisible(true);
 
            }else{
                        JOptionPane.showMessageDialog(this, "Juega con el metodo Poda Alfa-Beta \n para crear comparacion", "No es posible comparar", JOptionPane.ERROR_MESSAGE);
            }
        } else{
                              JOptionPane.showMessageDialog(this, "Juega con el metodo minimax \n para crear comparacion", "No es posible comparar", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnEstadosActionPerformed

    private void btnTiempoEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiempoEstadosActionPerformed
        // TODO add your handling code here:
                        if (!timeState.isEmpty()) {
            if (!timeStateAlpha.isEmpty()) {
                 XYSeries series = new XYSeries("Minimax");
  XYSeries series1 = new XYSeries("Poda Alpha-Beta");

  
        for (int i = 0; i < timeState.size(); i++) {
            series.add(i+1, timeState.get(i));
        }
        
               for (int i = 0; i < timeStateAlpha.size(); i++) {
            series1.add(i+1, timeStateAlpha.get(i));
        }
    XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(series);
         dataset.addSeries(series1);
         
              JFreeChart chart = ChartFactory.createXYLineChart(
                "Tiempo por estado de ejecucion turno", // Título
                "Turno", // Etiqueta Coordenada X
                "tiempo(Microsec)", // Etiqueta Coordenada Y
                dataset, // Datos
                PlotOrientation.VERTICAL,
                true, // Muestra la leyenda de los productos (Producto A)
                false,
                false
        );
              
        
                ChartFrame frame = new ChartFrame("Tiempo de ejecucion del turno ordenador", chart);
        frame.pack();
        frame.setVisible(true);
 
            }else{
                        JOptionPane.showMessageDialog(this, "Juega con el metodo Poda Alfa-Beta \n para crear comparacion", "No es posible comparar", JOptionPane.ERROR_MESSAGE);
            }
        } else{
                              JOptionPane.showMessageDialog(this, "Juega con el metodo minimax \n para crear comparacion", "No es posible comparar", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnTiempoEstadosActionPerformed

    private void btnStadisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStadisticsActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "Juegos ganados: "+gPlayer+ "\nJuegos Empatados: "+empate+ "\n juegos perdidos: "+gComputer, "Estadisticas", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnStadisticsActionPerformed


    public void juego(){
                
        System.out.println("You are Player 1!");
        System.out.println("Current board:");
        source.Map.printBoard(source.Map.map);
        System.out.println("Please pick a field from 1-9:");
    //     String name = JOptionPane.showInputDialog("Please pick a field from 1-9:");
    ///    int input =Integer.parseInt(name);
    createAndDisplayGUI();
        setO(input);
       
        while (input < 1 || input > 9) {
            System.err.println("Please input a number between 1 and 9");
         //             name = JOptionPane.showInputDialog("Please pick a field from 1-9:");
        // input =Integer.parseInt(name);
            createAndDisplayGUI();
            setO(input);
        }

        source.Map.map = source.Map.setTile(source.Map.map, input - 1, 0);
        source.Map.moves.remove(input - 1);
        System.out.println("Current board:");
        source.Map.printBoard(source.Map.map);

        for (int i = 0; i < 4; i++) {
            // MiniMax Opponent
            if (algoritmo == 0) {
                long start = System.nanoTime();
                MiniMaxSearch.miniMax(1);
                long end = System.nanoTime() - start;
                
                double time = 0;
               double statetime = 0; 
               double states = 0;
               states = source.Map.visitedStates;
               time =  (end / 1_000d);
              statetime = ((end / 1_000d) / source.Map.visitedStates);

              this.time.add(i, time);
              this.states.add(i,states);
              timeState.add(i, statetime);
                
                               String textMinimax ="Posicion movimiento: "+ (source.Map.returnMove + 1) + "\n";
                  textMinimax = textMinimax +"Tiempo:  microsec = " +  end / 1_000d+"\n" ;
                    textMinimax = textMinimax +"estados visitados: "+ source.Map.visitedStates+ "\n";
                       textMinimax = textMinimax +"tiempo/estados: microsec "+ (end / 1_000d) / source.Map.visitedStates+"\n\n";

                       txtMinimax.append(textMinimax);
  
                System.out.println("Your opponent picked: " + (source.Map.returnMove + 1));
                   setX(source.Map.returnMove + 1);
                source.Map.map = source.Map.setTile(source.Map.map, source.Map.returnMove, 1);
                source.Map.moves.remove(source.Map.returnMove);
                System.out.println("Current board:");
                source.Map.printBoard(source.Map.map);
                if (checkWin()) {
                                JOptionPane.showMessageDialog(this, finish, "Fin del juego", JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
            }
            // Alpha-Beta Opponent
            else {
                long start = System.nanoTime();
                AlphaBetaSearch.alphaBetaSearch(1);
                long end = System.nanoTime() - start;
                


                                double timeAlpha = 0;
               double statetimeAlpha = 0; 
               double statesAlpha = 0;
               statesAlpha = source.Map.visitedStates;
               timeAlpha =  (end / 1_000d);
              statetimeAlpha = ((end / 1_000d) / source.Map.visitedStates);

              this.timeAlpha.add(i, timeAlpha);
              this.statesAlpha.add(i, statesAlpha);
              timeStateAlpha.add(i, statetimeAlpha);
  
               
                String textAlpha ="Posicion movimiento: "+ (source.Map.returnMove + 1) + "\n";
                  textAlpha = textAlpha +"Tiempo:  microsec = " +  end / 1_000d+"\n" ;
                    textAlpha = textAlpha +"estados visitados: "+ source.Map.visitedStates+ "\n";
                       textAlpha = textAlpha +"tiempo/estados: microsec "+ (end / 1_000d) / source.Map.visitedStates+"\n\n";
                  //     txtPoda.setText(textAlpha);
                       txtPoda.append(textAlpha);
                 
                System.out.println("Your opponent picked: " + (source.Map.returnMove + 1));
                   setX(source.Map.returnMove + 1);
                source.Map.map = source.Map.setTile(source.Map.map, source.Map.returnMove, 1);
                source.Map.moves.remove(source.Map.returnMove);
                System.out.println("Current board:");
                source.Map.printBoard(source.Map.map);
                if (checkWin()) {
                                JOptionPane.showMessageDialog(this, finish, "", JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
            }

            System.out.println("Please pick a field from 1-9:");
    //            name = JOptionPane.showInputDialog("Please pick a field from 1-9:");
    //     input =Integer.parseInt(name);
        createAndDisplayGUI();
            setO(input);
            while (input < 1 || input > 9) {
                  System.err.println("Please input a number between 1 and 9");
       //           name = JOptionPane.showInputDialog("Please pick a field from 1-9:");
            //     input =Integer.parseInt(name);
                createAndDisplayGUI();
                 setO(input);
            }

            int tempMap = source.Map.setTile(source.Map.map, input - 1, 0);
            while (tempMap == Integer.MIN_VALUE) {
            //    input = sc.nextInt();
                createAndDisplayGUI();
                tempMap = source.Map.setTile(source.Map.map, input - 1, 0);
            }

            source.Map.map = source.Map.setTile(source.Map.map, input - 1, 0);
            source.Map.moves.remove(input - 1);
            System.out.println("Current board:");
            source.Map.printBoard(source.Map.map);
            if (checkWin()) {
                    JOptionPane.showMessageDialog(this, finish, "", JOptionPane.INFORMATION_MESSAGE);
                break;
            }

            source.Map.visitedStates = 0;
        }
    }
    
    
       private void createAndDisplayGUI()
       {       
           JOptionPane optionPane = new JOptionPane("Please pick a field from 1-9"
                                       , JOptionPane.PLAIN_MESSAGE
                                       , JOptionPane.DEFAULT_OPTION
                                       , null, null, "Please pick a field from 1-9");
           optionPane.setWantsInput(true);             
           JDialog dialog = optionPane.createDialog(null, "Tu Turno");
           dialog.setLocation(10, 20);
           dialog.setVisible(true);
           try{
           String name ="";
            name = (String) optionPane.getInputValue();
           input=0;
           System.out.println(name);
             input =Integer.parseInt(name);
           }catch(Exception e){
           JOptionPane.showMessageDialog(this, "Error al capturar numero: "+e, "Error",JOptionPane.ERROR_MESSAGE );
           }
       }
static int empate =0;
static int gPlayer =0;
static int gComputer =0;

    private static boolean checkWin() {
        switch (source.Map.utility(source.Map.map)) {
            case 0:
                System.out.println("Game done!\nDraw!");
             finish ="Juego Terminado \n EMPATE!";
            empate++;
                return true;
            case 1:
                System.out.println("Game done!\nYour opponent wins!");
                        finish = "Juego Terminado \n COMPUTADORA GANA!";
                        gComputer++;
                return true;
            case -1:
                System.out.println("Game done!\nYou win!");
                        finish ="Juego Terminado \n HAS GANADO!";
                        gPlayer++;
                return true;
        }

        return false;
    }
public void clear(){
       btn1.setText("");
       btn2.setText("");
       btn3.setText("");
       btn4.setText("");       
        btn5.setText("");
       btn6.setText("");
       btn7.setText("");
       btn8.setText("");     
       btn9.setText("");          

jugada=0;
  finish="";
  
source.Map.map=0;
source.Map.visitedStates = -10;

  // source.Map.returnMove = -1;

   source.Map.computerPlayer = -1;
   source.Map.message ="";
   source.Map.setHash();
}
    
public void setX(int posicion){
switch(posicion){
    case 1:
        btn1.setText("X");
       break;
     case 2:
        btn2.setText("X");         
       break; 
     case 3:
        btn3.setText("X");         
       break; 
     case 4:
         btn4.setText("X");        
       break;
     case 5:
         btn5.setText("X");        
       break; 
     case 6:
         btn6.setText("X");        
       break;          
    case 7:
        btn7.setText("X");        
       break;
     case 8:
        btn8.setText("X");         
       break; 
     case 9:
        btn9.setText("X");         
       break;
     default:
             JOptionPane.showMessageDialog(this, "ocurrio un error al mostrar la posicion", "", JOptionPane.ERROR_MESSAGE);
         break;
}

}

public void setO(int posicion){
switch(posicion){
    case 1:
        btn1.setText("O");
       break;
     case 2:
        btn2.setText("O");         
       break; 
     case 3:
        btn3.setText("O");         
       break; 
     case 4:
         btn4.setText("O");        
       break;
     case 5:
         btn5.setText("O");        
       break; 
     case 6:
         btn6.setText("O");        
       break;          
    case 7:
        btn7.setText("O");        
       break;
     case 8:
        btn8.setText("O");         
       break; 
     case 9:
        btn9.setText("O");         
       break;
     default:
             JOptionPane.showMessageDialog(this, "ocurrio un error al mostrar la posicion", "", JOptionPane.ERROR_MESSAGE);
         break;
}

}
    





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnEstados;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnStadistics;
    private javax.swing.JButton btnTiempo;
    private javax.swing.JButton btnTiempoEstados;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtMinimax;
    private javax.swing.JTextArea txtPoda;
    // End of variables declaration//GEN-END:variables

}
